### ISSUE TITLE
Duration timer bar displays incorrect time when station has started

### ISSUE THREAD

**Issue by Gumboot13** [rianadon/opensprinkler-card#21]
Just added the card and setup extra_entities to allow ease of starting stations from my phone etc.

Issue is when I start a station with a duration of 1 minute, it shows a durtaion of 5:32. The station only runs for the set time of 1 minute.

What ever I increase the timer by, increases it by that same amout in the duration (appears it adds 4:32 to the actually run time display)

**Comment by Gumboot13** [comment]
Appears it is only an issue if I access HA via my PC. Using the timer setting on my phone works as expected.

**Comment by rianadon** [comment]
Oh huh that's really odd. There's no way the PC time is 4 minutes behind, right?

It might be worth seeing if my [timer bar card](https://github.com/rianadon/timer-bar-card) has the same issue. The OpenSprinkler card uses this internally for creating the timers, but it's not using the most up-to-date version.

The actual timer logic has changed very little since the version embedded in the sprinkler card, but it has some extra functionality for [dealing with these out-of-sync issues](https://github.com/rianadon/timer-bar-card#sync-issues). It would be interesting to see if this fixes the issue.

**Comment by Gumboot13** [comment]
I will try via another PC and I will double check the time to ensure it's the same as opensprinkler.

If I still have issue I will give the timer bar card a go.

Cheers

**Comment by Gumboot13** [comment]
> Oh huh that's really odd. There's no way the PC time is 4 minutes behind, right?
> 
> It might be worth seeing if my [timer bar card](https://github.com/rianadon/timer-bar-card) has the same issue. The OpenSprinkler card uses this internally for creating the timers, but it's not using the most up-to-date version.
> 
> The actual timer logic has changed very little since the version embedded in the sprinkler card, but it has some extra functionality for [dealing with these out-of-sync issues](https://github.com/rianadon/timer-bar-card#sync-issues). It would be interesting to see if this fixes the issue.

You were correct. My PC time was out. Forgot to enable set time automatically in windows 

Problem solve and issue can be closed
