### ISSUE TITLE
Duplicate station names not handled correctly

### ISSUE THREAD

**Issue by klusekb** [rianadon/opensprinkler-card#9]
I have two OpenSprinkler controllers - one for the front yard and one for the backyard. There are multiple stations defined for each - 3 and 4, respectively. The remaining stations ("S0x") are unused.

I added both controllers to Home Assistant. There were no problems with the first one (front). However, when I added the second one (back), I only saw two stations instead of eight. I figured out that I only saw the two stations with unique names. The stations with names that were also present in "back" (including all the unused "S0x") were not visible.

I renamed the two stations I cared about, giving them unique names, removed and re-added the controller and the renamed stations are visible now. This makes me think that in a system with multiple sprinkler controllers, duplicate names are not handled properly.

The two controllers have unique names:
![os](https://user-images.githubusercontent.com/86543999/123570651-8825e200-d77d-11eb-8a82-2b47db13fe88.JPG)

The entities have unique names as well:
![stations](https://user-images.githubusercontent.com/86543999/123570714-a986ce00-d77d-11eb-8a55-c09c06873d58.JPG)

The "front" sprinkler card shows all stations, including the unused ones:
![front](https://user-images.githubusercontent.com/86543999/123570793-d20ec800-d77d-11eb-96f8-38d3b7cc9447.JPG)

The "back" sprinkler card only shows the station with unique names:
![back](https://user-images.githubusercontent.com/86543999/123570827-e05ce400-d77d-11eb-9674-bdfc17de2f93.JPG)

Might it be a display issue?

**Comment by rianadon** [comment]
Tricky tricky.

1. It looks like Home Assistant adds the `_2` to the end of the would-be-identical entity ids so that they are unique
2. The card expects the entity ids of the status entities to end with `_status`
3. `s05_station_status_2` does not end with `_status`. Hence it is not displayed 😭 

With #5 now merged, I think it might be safe to do away with the entity id checks. Thanks for giving me a great excuse to release yet another version!

**Comment by klusekb** [comment]
It appears to be working. Thanks!
